### ISSUE TITLE
No type check

### ISSUE THREAD

**Issue by ain** [rspec/rspec-collection_matchers#29]
If one has an object `Game` and a clause of 
``` ruby
it { is_expected.to have(100).games }
```
which prevails, and everything is fine, but the following will prevail also
``` ruby
it { is_expected.to have(100).slobodans }
```
which could be considered a bit off, no?

**Comment by soulcutter** [comment]
I believe this was intentional to allow users to write their tests expressively. Imagine using the matcher with a collection of objects of different types - you may want to refer to them by some abstract concept rather than type.

It can lead to nonsense as in your example.

**Comment by hugobarauna** [comment]
@ain 

Can you give me a code example, so I can help you?

From the info you gave us, I believe you're actually getting the correct behavior. Because the have matcher works in two scenarios:

1. when the subject (the object you're testing) is a collection
2. when the subject contains a collection

The scneario you described looks like the number 2.

**Comment by JonRowe** [comment]
@ain the feature you're using is syntactic sugar, its just checking for the presence of 100 things, the extra word has no meaning at all. It's one of the reasons why this was extracted from rspec in the first place. You can achieve your goals with:

```Ruby
it { is_expected.to all(be_an_instance_of Game).and have_attributes(size: 1000) }
# or if still using collection matchers
it { is_expected.to all(be_an_instance_of Game).and have(1000) }
```

**Comment by ain** [comment]
The `all` and `have_attributes` combo is exactly what I used. 

Based on your great responses, I'm considering the topic closed. Thanks guys.
